spring:
  kafka:
    template:
      default-topic: user-topic
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      group-id: console-consumer-70309
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer