spring:
  kafka:
    consumer:
      value-deserializer: com.jbignacio.kafkabindings.PayloadDeSerializer
      auto-offset-reset: earliest
  cloud:
    function:
      definition: consummer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: false
        bindings:
          processor-out-0:
            producer:
              configuration:
                value.serializer: com.jbignacio.kafkabindings.PayloadSerializer
          #supplier-out-0:
          #  producer:
          #    configuration:
          #      value.serializer: com.jbignacio.kafkabindings.PayloadSerializer
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.jbignacio.kafkabindings.PayloadDeSerializer
      bindings:
        processor-out-0:
          destination: order-events
          producer:
            use-native-encoding: true
        processor-in-0:
          destination: order-events
        #supplier-out-0:
        #  destination: order-events
        #  producer:
        #    use-native-encoding: true
        consummer-in-0:
          destination: order-events
          group: my-group
          consumer:
            use-native-decoding: true
